//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaileonTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.maileon.com/1.0/")]
        public string baseUri {
            get {
                return ((string)(this["baseUri"]));
            }
            set {
                this["baseUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5896e6bf-752b-4db3-955e-c24fc0479bd1")]
        public string apiKey {
            get {
                return ((string)(this["apiKey"]));
            }
            set {
                this["apiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1548")]
        public long mailingIdToDelete {
            get {
                return ((long)(this["mailingIdToDelete"]));
            }
            set {
                this["mailingIdToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1548")]
        public long mailingIdToSend {
            get {
                return ((long)(this["mailingIdToSend"]));
            }
            set {
                this["mailingIdToSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2665")]
        public long mailingIdExistingRegular {
            get {
                return ((long)(this["mailingIdExistingRegular"]));
            }
            set {
                this["mailingIdExistingRegular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long mailingIdExistingTrigger {
            get {
                return ((long)(this["mailingIdExistingTrigger"]));
            }
            set {
                this["mailingIdExistingTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long mailingIdExistingDoi {
            get {
                return ((long)(this["mailingIdExistingDoi"]));
            }
            set {
                this["mailingIdExistingDoi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2665")]
        public long mailingIdArchived {
            get {
                return ((long)(this["mailingIdArchived"]));
            }
            set {
                this["mailingIdArchived"] = value;
            }
        }
    }
}
